baseURL = 'https://latest-tech.online/'
languageCode = 'en-us'
title = 'NeuralNest'

[params]
  description = "Your source for the latest AI and tech news, tutorials, and reviews"
  author = "NeuralNest Team"
  mainSections = ["posts", "reviews"]
  # Added eye-friendly theme settings
  colorScheme = "blue"
  minimalUI = true
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Reviews"
    url = "/reviews/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4