baseURL = 'https://neuralnest.tech/'
languageCode = 'en-us'
title = 'NeuralNest'

[params]
  description = "Your source for the latest AI and tech news, tutorials, and reviews"
  author = "NeuralNest Team"
  mainSections = ["posts", "tutorials", "reviews", "news", "case-studies"]
  # Added eye-friendly theme settings
  colorScheme = "blue"
  minimalUI = true
  
  [params.social]
    twitter = "neuralnest"
    github = "neuralnest"
    linkedin = "neuralnest"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Tutorials"
    url = "/tutorials/"
    weight = 2
  [[menu.main]]
    name = "Reviews"
    url = "/reviews/"
    weight = 3
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 4
  [[menu.main]]
    name = "Case Studies"
    url = "/case-studies/"
    weight = 5
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6
